In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [3]:
x=np.array([[1,2,3],[4,5,6]])

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.shape(x)

(2, 3)

In [7]:
np.size(x)

6

In [9]:
np.ndim(x)

2

In [12]:
x.itemsize

4

In [14]:
x.dtype

dtype('int32')

In [15]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#reshape

In [39]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [41]:
#slicing

In [49]:
x[0]

array([1, 2, 3])

In [43]:
x[0,2]

3

In [44]:
x[1,1]

5

In [45]:
x[0:,0]

array([1, 4])

In [48]:
x[:-1]

array([[1, 2, 3]])

In [50]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
x[:-1]

array([[1, 2, 3]])

In [52]:
#row element accesing
x[:,0:2]

array([[1, 2],
       [4, 5]])

In [53]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
#row elemet accessing
y[1]

array([4, 5, 6])

In [60]:
#column accessing
y[:,2]

array([3, 6, 9])

In [63]:
#step
y[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [64]:
x.min()

1

In [65]:
x.max()

6

In [66]:
x.sum()

21

In [67]:
x.mean()

3.5

In [68]:
#acces=1 row
#acces=0 column
y.max(axis=1)

array([3, 6, 9])

In [70]:
y.sum(axis=0)

array([12, 15, 18])

In [71]:
np.sqrt(y)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [72]:
np.std(x)

1.707825127659933

In [ ]:
## vetical,horizental

In [73]:
a=np.array([[1,3,5],[3,4,5],[2,8,7]])
a

array([[1, 3, 5],
       [3, 4, 5],
       [2, 8, 7]])

In [75]:
b=np.array([[2,3,4],[3,4,5],[8,9,7]])
b

array([[2, 3, 4],
       [3, 4, 5],
       [8, 9, 7]])

In [76]:
np.vstack((a,b))

array([[1, 3, 5],
       [3, 4, 5],
       [2, 8, 7],
       [2, 3, 4],
       [3, 4, 5],
       [8, 9, 7]])

In [78]:
np.hstack((a,b))

array([[1, 3, 5, 2, 3, 4],
       [3, 4, 5, 3, 4, 5],
       [2, 8, 7, 8, 9, 7]])

In [79]:
np.ravel((a,b))

array([1, 3, 5, 3, 4, 5, 2, 8, 7, 2, 3, 4, 3, 4, 5, 8, 9, 7])

In [81]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
for i in np.arange(1,5):
    print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [87]:
np.tan(x)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [88]:
np.cos(a)

array([[ 0.54030231, -0.9899925 ,  0.28366219],
       [-0.9899925 , -0.65364362,  0.28366219],
       [-0.41614684, -0.14550003,  0.75390225]])

In [89]:
np.sin(b)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [ 0.98935825,  0.41211849,  0.6569866 ]])

## pandas

In [92]:
import pandas as pd

In [93]:
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

## creating a series datatype

In [94]:
s=pd.Series([1,2,3,35,7,57])

In [95]:
s

0     1
1     2
2     3
3    35
4     7
5    57
dtype: int64

In [98]:
s=pd.Series([1,2,3,35,7,57],index=['x','y','z','a','b','c'])

In [99]:
s

x     1
y     2
z     3
a    35
b     7
c    57
dtype: int64

In [100]:
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)
    Merge DataFrame or named Series objects with a database-style join.
    
    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    
    Parameters
    ----------
    left : DataFrame
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner'}, default 'inner'
        Type of merge to be performed.
    
        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key 

In [107]:
v1={1,2,3,4}
v2={4,5,6,7}
df=pd.DataFrame({'x':v1,'y':v2})

In [108]:
df

x             y
0  {1, 2, 3, 4}  {4, 5, 6, 7}
1  {1, 2, 3, 4}  {4, 5, 6, 7}
2  {1, 2, 3, 4}  {4, 5, 6, 7}
3  {1, 2, 3, 4}  {4, 5, 6, 7}

# pandas steps:
### -->1 slicing
### -->2 merging and joining
### -->3 concatination
### -->4 changing the index
### -->5 change column headers
### -->6 data munging

In [233]:
df=pd.DataFrame({'x':[20,32,34,21],'y':[6,7,56,5]},index=['a','b','c','d'],dtype=float)
df

x     y
a  20.0   6.0
b  32.0   7.0
c  34.0  56.0
d  21.0   5.0

In [387]:
data=[[20,30,40,50],[10,4,5],[7,8,9,4]]
df1=pd.DataFrame(data,columns=['x1','x2','x3','x4'])

In [388]:
df1

x1  x2  x3    x4
0  20  30  40  50.0
1  10   4   5   NaN
2   7   8   9   4.0

In [389]:
data=[[202,224,349,291],[45,367,478],[7,8,9,4]]
df2=pd.DataFrame(data,columns=['x1','x2','x3','x4'])

In [390]:
df2 

x1   x2   x3     x4
0  202  224  349  291.0
1   45  367  478    NaN
2    7    8    9    4.0

In [396]:
df2.isnull()

x1     x2     x3     x4
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False

In [397]:
df2.values

array([[202., 224., 349., 291.],
       [ 45., 367., 478.,  nan],
       [  7.,   8.,   9.,   4.]])

In [398]:
df2.ndim

2

In [399]:
df2.shape

(3, 4)

## 1 Slicling

In [400]:
df.head()

x1  x2  x3    x4
0  20  32  34  21.0
1   1   4   5   6.0
2   2  34  56   NaN

In [401]:
df.tail(1)

x1  x2  x3  x4
2   2  34  56 NaN

In [402]:
df1

x1  x2  x3    x4
0  20  30  40  50.0
1  10   4   5   NaN
2   7   8   9   4.0

In [403]:
df2

x1   x2   x3     x4
0  202  224  349  291.0
1   45  367  478    NaN
2    7    8    9    4.0

## merging and joining

In [404]:
# having same elements
pd.merge(df1,df2)

x1  x2  x3   x4
0   7   8   9  4.0

In [405]:
df1

x1  x2  x3    x4
0  20  30  40  50.0
1  10   4   5   NaN
2   7   8   9   4.0

In [406]:
df2

x1   x2   x3     x4
0  202  224  349  291.0
1   45  367  478    NaN
2    7    8    9    4.0

In [408]:
#two diffrent columns diffrent elements
j=df1.join(df2)
j

ValueError: columns overlap but no suffix specified: Index(['x1', 'x2', 'x3', 'x4'], dtype='object')

In [376]:
j

x1  x2  x3    x4  a  b    c
0  20  32  34  21.0  1  2  3.0
1  45  67  78   NaN  1  4  NaN
2   7   8   9   NaN  7  8  9.0

In [ ]:
# changing the column headers
