In [1]:
import pandas as pd
df= pd.DataFrame({'name':['janu','monu','gai','sai'],
                     'rollno':['502','504','506','508'],
                     'branch':['mech','cse','eee','civil']})
df

name rollno branch
0  janu    502   mech
1  monu    504    cse
2   gai    506    eee
3   sai    508  civil

In [2]:
df.loc[2]['branch']

'eee'

In [3]:
df.iloc[1]['name']

'monu'

In [4]:
df.count()

name      4
rollno    4
branch    4
dtype: int64

In [5]:
df.count(axis='rows')                            #check for row

name      4
rollno    4
branch    4
dtype: int64

In [6]:
df.count(axis='columns')                           #check for col

0    3
1    3
2    3
3    3
dtype: int64

In [7]:
df

name rollno branch
0  janu    502   mech
1  monu    504    cse
2   gai    506    eee
3   sai    508  civil

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
name      4 non-null object
rollno    4 non-null object
branch    4 non-null object
dtypes: object(3)
memory usage: 176.0+ bytes


In [9]:
df.describe()

name rollno branch
count      4      4      4
unique     4      4      4
top     janu    506  civil
freq       1      1      1

In [10]:
df.set_index(['rollno'])

name branch
rollno             
502     janu   mech
504     monu    cse
506      gai    eee
508      sai  civil

In [11]:
s=pd.Series(['a','b','c','d'])
s

0    a
1    b
2    c
3    d
dtype: object

In [12]:
s.describe()

count     4
unique    4
top       d
freq      1
dtype: object

In [13]:
import numpy as np
x=np.arange(0,9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
d=pd.DataFrame(np.arange(12).reshape(4,3),columns=['a','b','c'])
d

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [16]:
d=pd.DataFrame(np.arange(12).reshape(4,3),columns=list('abc'))
d

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [17]:
c=pd.DataFrame(np.arange(20).reshape(5,4),columns=list('pqrs'))
c

p   q   r   s
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [18]:
c.loc[2]['r']

10

In [19]:
c.loc[2,'r']=np.nan

In [20]:
c

p   q     r   s
0   0   1   2.0   3
1   4   5   6.0   7
2   8   9   NaN  11
3  12  13  14.0  15
4  16  17  18.0  19

In [21]:
c.isnull()

p      q      r      s
0  False  False  False  False
1  False  False  False  False
2  False  False   True  False
3  False  False  False  False
4  False  False  False  False

In [22]:
c.isnull().sum()

p    0
q    0
r    1
s    0
dtype: int64

In [23]:
d+c                                                     #for adding dataframes

a   b   c   p   q   r   s
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN NaN NaN

In [24]:
d.add(c)

a   b   c   p   q   r   s
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN NaN NaN

In [25]:
d.add(c,fill_value=5)


a     b     c     p     q     r     s
0   5.0   6.0   7.0   5.0   6.0   7.0   8.0
1   8.0   9.0  10.0   9.0  10.0  11.0  12.0
2  11.0  12.0  13.0  13.0  14.0   NaN  16.0
3  14.0  15.0  16.0  17.0  18.0  19.0  20.0
4   NaN   NaN   NaN  21.0  22.0  23.0  24.0

In [26]:
np.random.randn(1,10)

array([[ 0.93585985, -1.73518051,  0.99494704,  0.22226432, -0.62699065,
         2.54913926, -0.26504784, -0.03503548, -0.74841299,  3.70445492]])

In [27]:
np.random.rand(1,10)

array([[0.75904241, 0.84630284, 0.96693043, 0.09738015, 0.46365589,
        0.16841978, 0.35427853, 0.30535567, 0.65827191, 0.21618163]])

## creating dataframe with randomvalues

In [28]:
a=pd.DataFrame(np.random.randn(5,2))
a

0         1
0  0.284507 -0.860325
1  0.070057 -1.314375
2  1.321063  0.587969
3  2.020782  0.421837
4  0.471739 -1.041984

In [29]:
a=pd.DataFrame(np.random.randn(3,2),index=['a','b','c'])
a

0         1
a -0.366012  1.809675
b  0.617577  0.824674
c -0.259543  0.225791

In [30]:
a.columns=['x','y']
a

x         y
a -0.366012  1.809675
b  0.617577  0.824674
c -0.259543  0.225791

In [31]:
z=a.reindex(['p','q','r'])
z

x   y
p NaN NaN
q NaN NaN
r NaN NaN

In [32]:
z.isnull().sum()

x    3
y    3
dtype: int64

In [33]:
z.fillna(2)               # filling null values

x    y
p  2.0  2.0
q  2.0  2.0
r  2.0  2.0

In [34]:
z.dropna()              #drop(remove)null values

Empty DataFrame
Columns: [x, y]
Index: []

In [35]:
z.fillna(method='bfill',axis=0).fillna(1)           #backward filling

x    y
p  1.0  1.0
q  1.0  1.0
r  1.0  1.0

In [36]:
z.fillna(method='ffill',axis=0).fillna(2)           #forward filling

x    y
p  2.0  2.0
q  2.0  2.0
r  2.0  2.0

In [37]:
z.isna()                              #for checking null values

x     y
p  True  True
q  True  True
r  True  True

In [38]:
pd.isna(a['x'])                        # for checking null values in particular column

a    False
b    False
c    False
Name: x, dtype: bool

In [39]:
pd.isna(a['y'])

a    False
b    False
c    False
Name: y, dtype: bool

## Data replacing

In [40]:
f = pd.DataFrame({'A': [0, 1, 2, 3, 4],'C': [5, 6, 7, 8, 9],'B': ['a', 'b', 'c', 'd', 'e']})
f

A  C  B
0  0  5  a
1  1  6  b
2  2  7  c
3  3  8  d
4  4  9  e

In [41]:
f.replace(8,555)

A    C  B
0  0    5  a
1  1    6  b
2  2    7  c
3  3  555  d
4  4    9  e

In [42]:
f.replace([2,7],[333,333])

A    C  B
0    0    5  a
1    1    6  b
2  333  333  c
3    3    8  d
4    4    9  e

In [43]:
f.replace({0:22,5:66})

A   C  B
0  22  66  a
1   1   6  b
2   2   7  c
3   3   8  d
4   4   9  e

## sorting and reindexing

In [44]:
f.sort_index()

A  C  B
0  0  5  a
1  1  6  b
2  2  7  c
3  3  8  d
4  4  9  e

In [45]:
f.sort_index(axis=1)

A  B  C
0  0  a  5
1  1  b  6
2  2  c  7
3  3  d  8
4  4  e  9

# Group by

In [46]:
animal=pd.DataFrame({'name':['dog','cat','cow','dog','cow'],'place':['zoo','jungle','zoo','jungle','zoo'],"feature":['s','s','p','q','p']})
animal

name   place feature
0  dog     zoo       s
1  cat  jungle       s
2  cow     zoo       p
3  dog  jungle       q
4  cow     zoo       p

In [47]:
animal.groupby('name').sum()

place feature
name                   
cat      jungle       s
cow      zoozoo      pp
dog   zoojungle      sq

In [48]:
animal.groupby('feature').sum()

name      place
feature                   
p        cowcow     zoozoo
q           dog     jungle
s        dogcat  zoojungle

In [49]:
animal.groupby('feature').count()

name  place
feature             
p           2      2
q           1      1
s           2      2

In [50]:
animal.groupby(['name','feature']).sum()

place
name feature        
cat  s        jungle
cow  p        zoozoo
dog  q        jungle
     s           zoo

## Ranking

In [60]:
animal=pd.DataFrame({'name':['dog','cat','cow','dog','cow'],'place':['zoo','jungle','zoo','jungle','zoo'],"no of legs":[4,4,2,2,np.nan]})
animal

name   place  no of legs
0  dog     zoo         4.0
1  cat  jungle         4.0
2  cow     zoo         2.0
3  dog  jungle         2.0
4  cow     zoo         NaN

In [61]:
animal["ranks"]=animal['no of legs'].rank()

In [62]:
animal

name   place  no of legs  ranks
0  dog     zoo         4.0    3.5
1  cat  jungle         4.0    3.5
2  cow     zoo         2.0    1.5
3  dog  jungle         2.0    1.5
4  cow     zoo         NaN    NaN

In [63]:
animal["max_rank"]=animal["no of legs"].rank(method="max")
animal

name   place  no of legs  ranks  max_rank
0  dog     zoo         4.0    3.5       4.0
1  cat  jungle         4.0    3.5       4.0
2  cow     zoo         2.0    1.5       2.0
3  dog  jungle         2.0    1.5       2.0
4  cow     zoo         NaN    NaN       NaN

In [64]:
animal["first_rank"]=animal["no of legs"].rank(method="first")
animal

name   place  no of legs  ranks  max_rank  first_rank
0  dog     zoo         4.0    3.5       4.0         3.0
1  cat  jungle         4.0    3.5       4.0         4.0
2  cow     zoo         2.0    1.5       2.0         1.0
3  dog  jungle         2.0    1.5       2.0         2.0
4  cow     zoo         NaN    NaN       NaN         NaN

In [65]:
animal["non_rank"]=animal["no of legs"].rank(na_option="bottom")
animal

name   place  no of legs  ranks  max_rank  first_rank  non_rank
0  dog     zoo         4.0    3.5       4.0         3.0       3.5
1  cat  jungle         4.0    3.5       4.0         4.0       3.5
2  cow     zoo         2.0    1.5       2.0         1.0       1.5
3  dog  jungle         2.0    1.5       2.0         2.0       1.5
4  cow     zoo         NaN    NaN       NaN         NaN       5.0

In [66]:
animal["pct_rank"]=animal["no of legs"].rank(pct=True)
animal

name   place  no of legs  ranks  max_rank  first_rank  non_rank  pct_rank
0  dog     zoo         4.0    3.5       4.0         3.0       3.5     0.875
1  cat  jungle         4.0    3.5       4.0         4.0       3.5     0.875
2  cow     zoo         2.0    1.5       2.0         1.0       1.5     0.375
3  dog  jungle         2.0    1.5       2.0         2.0       1.5     0.375
4  cow     zoo         NaN    NaN       NaN         NaN       5.0       NaN

# Categorise

In [67]:
w=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
w

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [70]:
w["cc"]=w['y'].astype('category')
w

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [71]:
w["cc"]

0     6
1     7
2     8
3     9
4    10
Name: cc, dtype: category
Categories (5, int64): [6, 7, 8, 9, 10]

In [73]:
w["cc"].cat.categories=["good","bad","avg","worst","excellent"]
w

x   y         cc
0  1   6       good
1  2   7        bad
2  3   8        avg
3  4   9      worst
4  5  10  excellent

In [75]:
w["cc"]=w["cc"].set_categories=["good","bad","avg","worst","excellent"]
w

x   y         cc
0  1   6       good
1  2   7        bad
2  3   8        avg
3  4   9      worst
4  5  10  excellent

In [76]:
w.sort_values("cc")

x   y         cc
2  3   8        avg
1  2   7        bad
4  5  10  excellent
0  1   6       good
3  4   9      worst

In [77]:
w.groupby("cc").sum()

x   y
cc              
avg        3   8
bad        2   7
excellent  5  10
good       1   6
worst      4   9

In [78]:
w.groupby("cc").size()

cc
avg          1
bad          1
excellent    1
good         1
worst        1
dtype: int64

# Readind data

In [82]:
s=pd.read_table("sample.txt")
s

C:\Users\kvsw11\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


hello world 123345
0                 123
1                 456
2                 789

In [88]:
v=pd.read_table("ex1.csv",sep=',')
v

C:\Users\kvsw11\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo